### ISSUE TITLE
Error building PWM with mouse data

### ISSUE THREAD

**Issue by khoegenauer** [gacatag/IntEREst#2]
Attempted to build the PWM list using SpliceRack data for mouse. Got the following error:

> Error in Ops.data.frame(rbind(accAtacU12, rep(0.25, 4)), accGtagU12) : 
  '+' only defined for equally-sized data frames

Attempted again using U12DB data for mouse:

> Error in .normargPfm(x) : 
  invalid PFM 'x': IUPAC ambiguity letters are represented

Suggestions?

Running R 3.5.1 / BioConductor 3.7 (IntEREst 1.4.1) on Ubuntu 18.04.1

**Comment by gacatag** [comment]
Hi @khoegenauer .
The buildSsTypePwms() function with U12DB, for mouse used to work fine previously but now I also received an error from Biostrings::PWM() due to "N" characters in one of donor sequences in U12DB database (It does not accept any IUPAC code other than A, C, G and T). I added a filtering step now and it works fine.

The SpliceRack PWM tables for the mouse seem to be in different size compared to the human. I added codes to deal with the according to their size. It should work now but I would recommend using the U12DB.

I just managed to push the updates to Biconductor developer version (IntEREst v1.5.2). Unfortunately it seems that updates to release version of the packages in BioConductor 3.7 is not possible at the moment since BioConductor is upgrading to newer version but the new updates to the IntEREst should also be automatically available in the new release (Biocondcutor 3.8).
