### ISSUE TITLE
Building PWM matrix for hg38

### ISSUE THREAD

**Issue by amarinderthind** [gacatag/IntEREst#3]
Hi!
I aligned my data with hg38. So, I want to know Is it necessary to build a PWM matrix from scratch or can we use the matrix provided with the software? if it is not necessary, can I use the following in annotateU12 function of the program?

referenceChr=u12[ind,'chr'],
referenceBegin=u12[ind,'begin'],
referenceEnd=u12[ind,'end'],
refGenome= hg38.fa  

And If I understood properly, steps will be 
Build PWM, annotate12, referencePrepare and interest. 

Thank you very much in advance.

**Comment by gacatag** [comment]
Hi Amarinder!

The PWM is built from the U12DB so since it is human that you are studying you don't need to build it. You can use the _pwmU12db_ if you wish. Note that new features have recently been added to _buildSsTypePwms_ in case you wanted to experiment and generate new PWMs.

Regarding the pipeline you have it almost correct except that the order is slightly different:

  1. Build PWM (or use the available _pwmU12db_);
  2. Build a reference data.frame that includes exons and introns of the genes, using _referencePrepare_.*
  3. Annotate the U2/U2 introns in the reference data.frame using _annotate12_ and the built PWMs.
  4. Run _interest_ with "_IntRet_" mode to count reads that map to each intron.**

\* You can set the parameters so that it builds the reference using hg38 build and annotations from Esembl or RefSeq. Moreover, by default, the exonic regions are collapsed so that intronic regions remained in the final reference have no alternatively skipped exon affecting their read counts (but you can disable this option if you wish).

** If you are planning to run the analysis genome wide (not just limited to U12 genes) then run it in parallel on multiple cores (e.g. 40, 20, 10 or 8 if you are running on a server that supports that many computing cores) for a more robust run.

The mentioned pipeline (from 1 to 4) is suitable to compare the retention levels of U12-type introns to that of U2-type introns within samples, genome-wide, however if you wish to find significantly differentially retained introns across several samples my recommendation is that you run a couple of extra processes:

   5. After you ran 1 to 4 (I'll call the results from _"IntRet"_ run of interest 'IntRet result') run interest in _"IntSpan"_ mode of interest to get the exon-exon or intron spanning read counts (I'll call these 'intspan result').
   6. merge or cbind the IntRet result and IntSpan result.
   7. Add column/sample annotations to the merged results object with _addAnnotation_ as described in the vignette document ( [https://bioconductor.org/packages/release/bioc/vignettes/IntEREst/inst/doc/IntEREst.html#difanalysis](url) )
  8. Extract intron rows from the merged object.
  9. Run differential retention analysis as described in the vignette ( Our recommended pipeline ... ) to get adjusted Pvalues, logFC and etc.

BTW, the _u12_ data.frame that you mentioned is just a test reference data, as I mentioned above you have to built your own reference either from Ensembl or Refeseq. For RefSeq and hg19 I used this command:
```
refseqRef<- referencePrepare (sourceBuild="UCSC", ucscGenome="hg19",
    addCollapsedTranscripts=TRUE, ignore.strand=FALSE)
```

I think the table name has changed for the hg38 in UCSC (see `rtracklayer::supportedUCSCtables(genome="hg38")` ). The following seems to work when I tested.

```
refseqRef<- referencePrepare (sourceBuild="UCSC", ucscGenome="hg38",
     addCollapsedTranscripts=TRUE, ignore.strand=FALSE, ucscTableName="refGene")

```
Hope these info are helpful. Feel free to let me know if you had any other problems or questions.

Cheers,

**Comment by amarinderthind** [comment]
Dear Ali,

thank you very much for your reply. I have another question regarding the Pipeline. I have a plan to use the available "pwmU12db". 

But for step 2: I would like to build my reference data.frame from GFF3 file, which I provided in star software at the time of alignment. [i.e a user-defined file]. An example provided by you uses u12IntronsBeg and u12IntronsEnd from "u12 data". ( to assign "int_type" column in the reference) 

I did not understand the concept here in my case... how does the software use the co-ordinate of already existing  "u12 data" which is built from hg19 reference (I guess) while the newly provided GFF3/GTF file is based on hg38?  

Also in the example, same coordinates of u12 are used for "u2/u12 annotation" (step3). 
I would like to know how it works? 
Can I create reference and annotation without providing u12 co-ordinates? 

thank you very much for your help and time.

**Comment by amarinderthind** [comment]
Dear Ali,

Thank . you very much for the answers. 
I will prefer to use PWM. 
I have a question regarding building a reference,

**Comment by gacatag** [comment]
Hi Amarinder!
If you have the coordinates of the U12-type introns in the genome, you can provide them as input when building a reference dataframe and this would result to an extra column in the dataframe output that shows  introns that match your entry i.e. U12-type introns, and those that don't (U2-type introns); but this is not mandatory. If you don't have the coordinates of the U12 type introns (for hg38 as for instance) just build the reference df without filling the _u12IntronsChr_, _u12IntronsBeg_ parameters.You can  then apply the _annotateU12()_ on the reference df to discover the U12-type introns using the PWM.

**Comment by gacatag** [comment]
You can also see an example of the procedure of building reference (it is from hg19) and annotating it in the [supplemenrat file 1](https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-018-2122-5/MediaObjects/12859_2018_2122_MOESM1_ESM.html) of the [Interest paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2122-5)

**Comment by amarinderthind** [comment]
thank you very much. This is what I was looking for.
