### ISSUE TITLE
FPKM clarification

### ISSUE THREAD

**Issue by Aufiero** [gacatag/IntEREst#8]
Hi,

I have a question about the FPKM normalized read counts that you reported in your paper.
What I understand is this:
E.g. for a generic gene A with 3 introns X, Y and Z
FPKM for intron X = (reads mapping to X / (length intron X * reads mapping to introns X, Y, Z)) * 10^9
Is that correct?

I have 2 questions:
Why is it considered the length of the other introns in the formula?
What about normalization for library size?
 
Should FPKM be calculate in this way:
normalization factor = total mapped reads/ 100000 
normalized intron length = length intron X / 1000
RPM = reads mapping to intron X / normalization factor (Here we normalize for library size)
FPKM for intron X = RPM / normalized intron length (Here we normalize for the length of the intron)

Thanks.
S

**Comment by gacatag** [comment]
Hello.
> Hi,
> 
> I have a question about the FPKM normalized read counts that you reported in your paper.
> What I understand is this:
> E.g. for a generic gene A with 3 introns X, Y and Z
> FPKM for intron X = (reads mapping to X / (length intron X * reads mapping to introns X, Y, Z)) * 10^9
> Is that correct?
> 
> I have 2 questions:
> Why is it considered the length of the other introns in the formula?

Sorry I didn't understand your question! So... Longer introns have more reads mapped to them, that's why the intron retention (IR) levels that are measured by the number of reads mapped to the intron should be corrected to the length of the intron.

> What about normalization for library size?

The library size affects the gene expression and the IR. because the number of reads that map to the introns is divided to the sum of the number of reads that map to the introns of the gene (i.e. introns X,Y, and Z in your example), and due to the fact that both of these are affected by the library size bias, they would be evened out. Moreover, note that we usually use these FPKM normalized IR levels for comparing the retention of each U12-type introns to its flanking U2-type introns (within the same gene and sample).

> Should FPKM be calculate in this way:
> normalization factor = total mapped reads/ 100000
> normalized intron length = length intron X / 1000
> RPM = reads mapping to intron X / normalization factor (Here we normalize for library size)
> FPKM for intron X = RPM / normalized intron length (Here we normalize for the length of the intron)

FPKM was originally defined for gene expression analysis. We used a **semi-FPKM** method that is basically the same idea but on the intron-exon scale, because our goal was to compare the retention of different types of introns within a sample. Do note that if the goal is to compare across samples [TPM](https://www.rna-seqblog.com/rpkm-fpkm-and-tpm-clearly-explained/) would be a better measurement. It is basically similar to FPKM (different order of length and lib. size normalizations however) but it is scaled to sums to 1million within each sample. In future I will add an option to the IR measurement functions to scale the normalised read counts to sum to one million in each sample. 

Also do note that as mentioned [in our IntEREst paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2122-5) for cross-sample IR comparison and differential analyses the DESeq2 and the actual read counts (without any FPKM/TPM normlization) were used. DESEq2 uses its own preprocessing and normlization however.

> Thanks.
> S
